name: Run Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test

      - name: Generate HTML report
        run: |
          npm run report:generate
          mkdir -p cypress-artifacts
          cp -r cypress/reports/html cypress-artifacts/

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress-artifacts/html
